### ISSUE TITLE
gradlew/gradlew.bat should be respected

### ISSUE THREAD

**Issue by steffsommer** [andy-bell101/neotest-java#8]
Currently the adapter relies on the gradle installation available in `PATH`.
Since Gradle has quite a few breaking changes between major releases, their recommendation is to run the Gradle Wrapper using the (`gradlew`/`gradlew.bat`) scripts. 

the neotest-java adapter should look for those scripts in the root directory and execute the one appropriate for the OS.

**Comment by andy-bell101** [comment]
Hopefully the latest commit should include this functionality. I don't have a windows machine to test on though so your help would be appreciated

**Comment by andy-bell101** [comment]
Looks like I spoke too soon. Thought I should add test cases for completeness and I can't get them to pass

**Comment by andy-bell101** [comment]
Ok test cases are in now and they pass

**Comment by steffsommer** [comment]
It works. `gradlew.bat` is now used. Thanks!
